# Generated by Django 4.2.28 on 2026-02-07 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_complaints', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='families.family')),
                ('visit', models.ForeignKey(blank=True, db_column='visit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='visits.visit')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
        migrations.CreateModel(
            name='ComplaintMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_column='author_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='complaint_messages', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(db_column='complaint_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='complaints.complaint')),
            ],
            options={
                'db_table': 'complaint_messages',
                'indexes': [models.Index(fields=['complaint', 'created_at'], name='complaint_msgs_thread_idx'), models.Index(fields=['id', 'complaint'], name='complaint_msgs_id_compl_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['family'], name='complaints_family_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-created_at'], name='complaints_status_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['priority', '-created_at'], name='complaints_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_by'], name='complaints_created_by_idx'),
        ),
    ]
