# Generated by Django 4.2.28 on 2026-02-07 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.TextField(help_text='Base64url-encoded credential ID', unique=True)),
                ('public_key', models.BinaryField(help_text='COSE public key bytes')),
                ('sign_count', models.BigIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, help_text='e.g. ["internal","hybrid"]', null=True)),
                ('aaguid', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webauthn_credentials',
                'indexes': [models.Index(fields=['user'], name='webauthn_user_idx')],
            },
        ),
    ]
