# Generated by Django 4.2.28 on 2026-02-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitAttestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('signed', 'Signed'), ('cannot_sign', 'Cannot Sign')], max_length=15)),
                ('signer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('signer_role', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('family_member', 'Family Member'), ('witness', 'Witness')], max_length=15)),
                ('signature_svg', models.TextField(blank=True, help_text='SVG path data for the signature. Required if status=signed.', null=True)),
                ('reason_cannot_sign', models.TextField(blank=True, help_text='Required if status=cannot_sign.', null=True)),
                ('witness_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.IntegerField(blank=True, null=True)),
                ('client_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_attestations', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(db_column='visit_id', on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='visits.visit')),
            ],
            options={
                'db_table': 'visit_attestations',
                'indexes': [models.Index(fields=['visit'], name='attestation_visit_idx'), models.Index(fields=['created_by'], name='attestation_created_by_idx'), models.Index(fields=['status', '-created_at'], name='attestation_status_idx')],
            },
        ),
    ]
