# Generated by Django 4.2.28 on 2026-02-07 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_short', models.CharField(max_length=6, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_cards', to='families.family')),
                ('revoked_by', models.ForeignKey(blank=True, db_column='revoked_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_cards', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, db_column='visit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_cards', to='visits.visit')),
            ],
            options={
                'db_table': 'beneficiary_cards',
                'indexes': [models.Index(fields=['family'], name='benef_cards_family_idx'), models.Index(fields=['expires_at'], name='benef_cards_expires_idx')],
            },
        ),
    ]
