# Generated by Django 4.2.28 on 2026-02-07 08:58
# Manually fixed: split access_token into add-nullable → backfill → add-unique

import secrets

import apps.cards.models
from django.db import migrations, models


def backfill_access_tokens(apps, schema_editor):
    """Generate a unique access_token for every existing BeneficiaryCard."""
    BeneficiaryCard = apps.get_model("cards", "BeneficiaryCard")
    for card in BeneficiaryCard.objects.filter(access_token__isnull=True):
        card.access_token = secrets.token_urlsafe(48)[:64]
        card.save(update_fields=["access_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        # 1. access_count — safe, has default=0
        migrations.AddField(
            model_name='beneficiarycard',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        # 2. access_token — add as NULLABLE first (no unique yet)
        migrations.AddField(
            model_name='beneficiarycard',
            name='access_token',
            field=models.CharField(max_length=64, null=True, blank=True),
        ),
        # 3. Backfill existing rows with unique tokens
        migrations.RunPython(backfill_access_tokens, migrations.RunPython.noop),
        # 4. Now make it non-null + unique + default
        migrations.AlterField(
            model_name='beneficiarycard',
            name='access_token',
            field=models.CharField(
                default=apps.cards.models._generate_access_token,
                max_length=64,
                unique=True,
            ),
        ),
        # 5. last_accessed_at — safe, nullable
        migrations.AddField(
            model_name='beneficiarycard',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
