# Generated by Django 4.2.28 on 2026-02-07 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('visit', 'Visit'), ('complaint_message', 'Complaint Message')], max_length=20)),
                ('owner_id', models.UUIDField()),
                ('mime_type', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.TextField()),
                ('size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['owner_type', 'owner_id'], name='attachments_owner_lookup_idx'), models.Index(fields=['uploaded_by'], name='attachments_uploader_idx'), models.Index(fields=['-created_at'], name='attachments_created_idx')],
            },
        ),
    ]
