# Generated by Django 4.2.28 on 2026-02-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='owner_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('complaint_message', 'Complaint Message'), ('emergency_incident', 'Emergency Incident')], max_length=20),
        ),
    ]
