# Generated by Django 4.2.28 on 2026-02-07 06:09

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_name', models.CharField(max_length=255)),
                ('household_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('vulnerability_notes', models.TextField(blank=True, null=True)),
                ('zone_label', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('priority_override', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('normal', 'Normal')], max_length=10, null=True)),
                ('has_accessibility_need', models.BooleanField(default=False)),
                ('accessibility_types', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('accessibility_verification', models.CharField(choices=[('none', 'None'), ('declared', 'Declared'), ('verified', 'Verified')], default='none', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_used', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_families', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_families', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'families',
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_ar', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vulnerability_tags',
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='vuln_tags_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyVulnerabilityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.family')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.vulnerabilitytag')),
            ],
            options={
                'db_table': 'family_vulnerability_tags',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='vulnerability_tags',
            field=models.ManyToManyField(blank=True, related_name='families', through='families.FamilyVulnerabilityTag', to='families.vulnerabilitytag'),
        ),
        migrations.AddIndex(
            model_name='familyvulnerabilitytag',
            index=models.Index(fields=['tag'], name='family_vuln_tags_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='familyvulnerabilitytag',
            constraint=models.UniqueConstraint(fields=('family', 'tag'), name='family_vuln_tags_pkey'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['created_by'], name='families_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['assigned_to'], name='families_assigned_to_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['zone_label'], name='families_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['next_due_at'], name='families_next_due_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['last_visit_at'], name='families_last_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['lat', 'lng'], name='families_lat_lng_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['next_due_at', 'last_visit_at'], name='families_due_sort_idx'),
        ),
    ]
