# Generated by Django 4.2.28 on 2026-02-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['lat'], name='families_lat_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['lng'], name='families_lng_idx'),
        ),
    ]
