# Generated by Django 4.2.28 on 2026-02-07 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0002_family_families_lat_idx_family_families_lng_idx'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label_fr', models.CharField(max_length=120)),
                ('label_ar', models.CharField(max_length=120)),
                ('severity_level', models.SmallIntegerField(help_text='1 (low) to 5 (critical)')),
                ('is_agent_safety', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'emergency_types',
            },
        ),
        migrations.CreateModel(
            name='EmergencyIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('severity_level', models.SmallIntegerField(help_text='Snapshot from EmergencyType at creation time.')),
                ('summary', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('trigger_method', models.CharField(choices=[('long_press', 'Long Press'), ('slide', 'Slide'), ('admin', 'Admin')], default='slide', max_length=15)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.IntegerField(blank=True, null=True)),
                ('network_state', models.CharField(choices=[('online', 'Online'), ('offline_queued', 'Offline (queued)')], default='online', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('assigned_admin', models.ForeignKey(blank=True, db_column='assigned_admin_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergencies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='emergency_incidents', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, db_column='family_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_incidents', to='families.family')),
                ('type', models.ForeignKey(db_column='emergency_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='emergencies.emergencytype')),
                ('visit', models.ForeignKey(blank=True, db_column='visit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_incidents', to='visits.visit')),
            ],
            options={
                'db_table': 'emergency_incidents',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('note', 'Note'), ('status_change', 'Status Change'), ('notify', 'Notify'), ('call', 'Call'), ('dispatch', 'Dispatch'), ('assign', 'Assign')], max_length=15)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_actions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='emergencies.emergencyincident')),
            ],
            options={
                'db_table': 'emergency_actions',
            },
        ),
        migrations.AddIndex(
            model_name='emergencyincident',
            index=models.Index(fields=['status', '-created_at'], name='emerg_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyincident',
            index=models.Index(fields=['created_by', '-created_at'], name='emerg_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyincident',
            index=models.Index(fields=['family', '-created_at'], name='emerg_family_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyincident',
            index=models.Index(fields=['visit'], name='emerg_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyaction',
            index=models.Index(fields=['incident', 'created_at'], name='emerg_actions_incident_idx'),
        ),
    ]
