# Generated by Django 4.2.28 on 2026-02-07 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visited_at', models.DateTimeField()),
                ('motive', models.CharField(choices=[('distribution', 'Distribution'), ('follow_up', 'Follow-up'), ('assessment', 'Assessment'), ('emergency', 'Emergency')], max_length=20)),
                ('visit_lat', models.FloatField(blank=True, null=True)),
                ('visit_lng', models.FloatField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('urgent_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='families.family')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
        migrations.CreateModel(
            name='VisitAid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note_short', models.CharField(blank=True, max_length=140, null=True)),
                ('is_urgent', models.BooleanField(blank=True, null=True)),
                ('aid_type', models.ForeignKey(db_column='aid_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='visit_aids', to='aids.aidtype')),
                ('visit', models.ForeignKey(db_column='visit_id', on_delete=django.db.models.deletion.CASCADE, related_name='aids', to='visits.visit')),
            ],
            options={
                'db_table': 'visit_aids',
                'indexes': [models.Index(fields=['visit'], name='visit_aids_visit_idx'), models.Index(fields=['aid_type'], name='visit_aids_aid_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='visitaid',
            constraint=models.UniqueConstraint(fields=('visit', 'aid_type'), name='visit_aids_unique'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['family', '-visited_at'], name='visits_family_visited_desc'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['-visited_at'], name='visits_visited_at_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['next_due_at'], name='visits_next_due_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['created_by'], name='visits_created_by_idx'),
        ),
    ]
