# Generated by Django 4.2.28 on 2026-02-07 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AidType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_ar', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aid_types',
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='aid_types_active_idx')],
            },
        ),
    ]
